version: "2"

services:
  api:
    build: .
    command: lein run :nrepl :api :deposit-api
    links:
      - elasticsearch
    environment:
      - API_PORT=3000
      - NREPL_PORT=7880
    ports:
      - 3000:3000
      - 7880:7880
    volumes:
    - .:/usr/src/app
    - ./.m2-cache:/root/.m2
    working_dir: "/usr/src/app"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
networks:
  default:
    external:
      name: cayenne_default
