version: "2"

services:
  api:
    build: .
    command: lein run :nrepl :api :deposit-api
    links:
      - elasticsearch
    environment:
      - API_PORT=3000
      - NREPL_PORT=7880
    ports:
      - 80:3000
      - 7880:7880
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
networks:
  default:
    external:
      name: cayenne_default
